PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 9,
  "title": "Updated Post Title 6 with typescript",
  "postType": "post",
  "status": "draft",
  "content": "Test content",
  "tags": [1, 3]  
}